services:
  - type: web
    name: dash-app
    env: python
    region: oregon # ou un autre emplacement selon votre choix
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
